# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-02 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('colaborador_cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('colaborador_sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], default='masculino', max_length=11, verbose_name='Sexo')),
                ('colaborador_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('colaborador_admissao', models.DateField(default=datetime.date(2017, 8, 2), verbose_name='Data de Admissão')),
                ('colaborador_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('colaborador_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franquia_descricao', models.CharField(max_length=11, verbose_name='Franquia')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao_descricao', models.CharField(max_length=25, verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
            },
        ),
        migrations.AddField(
            model_name='franquia',
            name='franquia_limites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibcolaboradores.Funcao'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='colaborador_franquia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mibcolaboradores.Franquia'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='colaborador_funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibcolaboradores.Funcao'),
        ),
    ]
