# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-02 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibcolaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franquia',
            old_name='franquia_limites',
            new_name='franquia_funcao',
        ),
        migrations.AddField(
            model_name='franquia',
            name='franquia_limite',
            field=models.IntegerField(default=0, verbose_name='Limite'),
        ),
    ]
