# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-05 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibcolaboradores', '0003_auto_20170805_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franquia',
            name='franquia_funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibcolaboradores.Funcao'),
        ),
    ]
