# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-01 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibcolaboradores', '0004_auto_20170805_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='colaborador_admissao',
            field=models.DateField(default=datetime.date(2017, 9, 1), verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='colaborador_cpf',
            field=models.CharField(help_text='Apenas números', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='colaborador_nascimento',
            field=models.DateField(help_text='EX: 01/01/1901', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='franquia',
            name='franquia_funcao',
            field=models.ForeignKey(help_text='Atenção: Não repita função para a mesma franquia', on_delete=django.db.models.deletion.CASCADE, to='mibcolaboradores.Funcao'),
        ),
    ]
