# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibcolaboradores', '0005_auto_20170901_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ['colaborador_nome'], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='franquia',
            options={'ordering': ['franquia_descricao'], 'verbose_name': 'Franquia', 'verbose_name_plural': 'Franquias'},
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='colaborador_admissao',
            field=models.DateField(default=datetime.date(2017, 9, 14), verbose_name='Data de Admissão'),
        ),
    ]
