"""
Django settings for mibcolaboradores project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0*+&_zs&_8d9lk7k2a#^lq)23g1e8&(8^i#n88d=4nz1#ixr$i'

# SECURITY WARNING: don't run with debug turned on in production!
#produção
#DEBUG = False
#desenvolvimento
DEBUG = True

ALLOWED_HOSTS = [
    '*'
    ]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mibcolaboradores',
    'localflavor',
    'mibcolaboradores.templatetags',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mibcolaboradores.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mibcolaboradores.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

#produção
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'colaboradores',
#        'HOST': 'db',
#        'USER': 'root',
#        'PASSWORD': 'masterkey',
#        'OPTIONS': {
#             'init_command': 'SET default_storage_engine=INNODB',
#        }
#    }
#}

#desenvolvimento
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'colaboradores',
        'HOST': 'localhost',
        'USER': 'thijeremias',
        'PASSWORD': '',
        'OPTIONS': {
             'init_command': 'SET default_storage_engine=INNODB',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
#Alias /static/admin/ "/home/ubuntu/workspace/env/lib/python3.5/site-packages/django/contrib/admin/static/admin/"

#descomentar a linha abaixo, quando em produção
#STATIC_ROOT = '/static/'
STATIC_URL = '/static/'
LOGIN_URL = '/'

#configuração para envio de e-mails
#comentar primeira linha quando em produção
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'thi.jeremias@gmail.com'
EMAIL_HOST_PASSWORD = '"4N&,q26'
SERVER_EMAIL = 'administrador@mibcolaboradores.org'
DEFAULT_TO_EMAIL = [
    'eduardo@lojasmib.com.br', 
    'thiago@lojasmib.com.br',
    ]
ADMINS = [
          ('Thiago','thiago@lojasmib.com.br'),
     ]